# This workflow executes the gradle build.
# It is triggered on a push or a pull request on develop branch.
# Generated APKs are uploaded as artifacts

name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Generate APK artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # A complete fetch needed for spotless to ratchet from origin/develop
          fetch-depth: 0

      # Set up JDK
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Cache gradle to speed up the build
      - name: Cache Gradle and Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # Grant Permission to Execute gradlew
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      
      # Build
      - name: Build
        run: bash ./gradlew build --stacktrace
        
      # Generate Signing Report
      - name: Generate Signing Report
        run: |
          cd app
          keytool -genkey -noprompt -keystore debug.keystore -storepass android -alias androiddebugkey -dname "C=US, O=Android, CN=Android Debug" -keypass android -keyalg RSA -keysize 2048 -validity 10000
          cd ..
          bash ./gradlew signingReport
      
      # Upload the generated APKs to the artifacts
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: |
            app/build/outputs/apk/debug/app-debug.apk
